sudo: required

env:
  HADOLINT: "${HOME}/hadolint"

language: node_js

node_js:
  - node

services:
  - docker

addons:
  apt:
    packages:
      - shellcheck
        #- hadolint

before_script:
  # - make -B
  - docker ps -a

install:
  # Download hadolint binary and set it as executable
  - curl -sL -o ${HADOLINT} "https://github.com/hadolint/hadolint/releases/download/v1.2.4/hadolint-$(uname -s)-$(uname -m)" && chmod 700 ${HADOLINT}

script:
  - git ls-files --exclude='Dockerfile*' --ignored | xargs --max-lines=1 ${HADOLINT}
  - shellcheck *.sh

    #deploy:
    #  provider: script
    #  skip_cleanup: true
    #  script:
    #    - yarn docs
