sudo: required

language: node_js

node_js:
  - node

services:
  - docker

addons:
  apt:
    sources:
      - debian-sid    # Grab ShellCheck from the Debian repo
    packages:
      - shellcheck

before_script:
  - make -B
  - docker ps -a

script:
  - shellcheck *.sh

deploy:
  provider: script
  skip_cleanup: true
  script:
    - yarn docs
